name: Alert `website` repository on push
on: push

jobs:
  build:
    name: Dispatch to `website` repository for regeneration of documents
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: peter-evans/repository-dispatch@v1.1.1
        with:
          token: ${{ secrets.HUGO_DEPLOY_TOKEN }}
          repository: smart-swimmingpool/website.git
          event-type: doc_update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
